-- ============================================================================
-- GENERATED IMAGES STORAGE BUCKET (PRIVATE)
-- ============================================================================
-- Storage for AI-generated images from chat (scientific visualizations)
-- Uses signed URLs for secure, time-limited access.
--
-- NOTE: The bucket must be created manually in Supabase Dashboard:
-- 1. Go to Storage in Supabase Dashboard
-- 2. Create bucket named "generated-images"
-- 3. Keep "Public bucket" DISABLED (private)
-- 4. Set file size limit to 10MB
-- 5. Allow MIME types: image/png, image/jpeg, image/webp
--
-- This migration sets up the RLS policies for the bucket.
-- Access is via signed URLs generated by the backend (service role).

-- Service role can read images (for generating signed URLs)
CREATE POLICY "Service role read for generated images"
ON storage.objects FOR SELECT
USING (bucket_id = 'generated-images');

-- Service role can insert images (backend uploads)
CREATE POLICY "Service role insert for generated images"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'generated-images');

-- Service role can update images
CREATE POLICY "Service role update for generated images"
ON storage.objects FOR UPDATE
USING (bucket_id = 'generated-images');

-- Service role can delete old images (cleanup)
CREATE POLICY "Service role delete for generated images"
ON storage.objects FOR DELETE
USING (bucket_id = 'generated-images');
